module.exports = getOperationType = (operationType) => {
  const operationTypes = {
    1.0: "null",
    1.1: "base",
    1.2: "account",
    1.3: "asset",
    1.4: "force_settlement",
    1.5: "committee_member",
    1.6: "witness",
    1.7: "limit_order",
    1.8: "call_order",
    1.9: "custom",
    1.1: "proposal",
    1.11: "operation_history",
    1.12: "withdraw_permission",
    1.13: "vesting_balance",
    1.14: "worker",
    1.15: "balance",
    1.16: "htlc",
    1.17: "custom_authority",
    1.18: "ticket",
    1.19: "liquidity_pool",
    1.2: "samet_fund",
    1.21: "credit_offer",
    1.22: "credit_deal",
    2.0: "global_property",
    2.1: "dynamic_global_property",
    2.2: "reserved0",
    2.3: "asset_dynamic_data",
    2.4: "asset_bitasset_data",
    2.5: "account_balance",
    2.6: "account_statistics",
    2.7: "transaction_history",
    2.8: "block_summary",
    2.9: "account_history",
    2.1: "blinded_balance",
    2.11: "chain_property",
    2.12: "witness_schedule",
    2.13: "budget_record",
    2.14: "special_authority",
    2.15: "buyback",
    2.16: "fba_accumulator",
    2.17: "collateral_bid",
    2.18: "credit_deal_summary",
  };

  return operationTypes[operationType] || "unknown";
};
