module.exports = getOperationType = (operationType) => {
  const operationTypes = {
    0: "transfer",
    1: "limit_order_create",
    2: "limit_order_cancel",
    3: "call_order_update",
    4: "fill_order",
    5: "account_create",
    6: "account_update",
    7: "account_whitelist",
    8: "account_upgrade",
    9: "account_transfer",
    10: "asset_create",
    11: "asset_update",
    12: "asset_update_bitasset",
    13: "asset_update_feed_producers",
    14: "mint" /*asset_issue*/,
    15: "asset_reserve",
    16: "asset_fund_fee_pool",
    17: "asset_settle",
    18: "asset_global_settle",
    19: "asset_publish_feed",
    20: "witness_create",
    21: "witness_update",
    22: "proposal_create",
    23: "proposal_update",
    24: "proposal_delete",
    25: "withdraw_permission_create",
    26: "withdraw_permission_update",
    27: "withdraw_permission_claim",
    28: "withdraw_permission_delete",
    29: "committee_member_create",
    30: "committee_member_update",
    31: "committee_member_update_global_parameters",
    32: "vesting_balance_create",
    33: "vesting_balance_withdraw",
    34: "worker_create",
    35: "custom",
    36: "assert",
    37: "balance_claim",
    38: "override_transfer",
    39: "transfer_to_blind",
    40: "blind_transfer",
    41: "transfer_from_blind",
    42: "asset_settle_cancel",
    43: "asset_claim_fees",
    44: "bid_collateral",
    45: "execute_bid",
    46: "asset_claim_pool",
    47: "asset_update_issuer",
    48: "htlc_create",
    49: "htlc_redeem",
    50: "htlc_redeemed",
    51: "htlc_extend",
    52: "htlc_refund",
  };

  return operationTypes[operationType] || "unknown";
};
